require 'bundler/gem_tasks'
require 'yard'
require 'rspec/core/rake_task'

YARD::Rake::YardocTask.new do |t|
  t.files   = ['lib/**/*.rb']   # optional
  t.options = ['--output-dir=doc'] # optional
end

RSpec::Core::RakeTask.new(:spec)
